# Generated by Django 4.1.5 on 2023-01-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('shd', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('Author', models.CharField(max_length=20)),
            ],
        ),
    ]
